upstream moqui_upstream {
  server moqui:8080 max_fails=10 fail_timeout=10s;
  keepalive 64;
}

map $http_x_forwarded_proto $forwarded_proto {
  default $scheme;
}

server {
  listen 80;
  server_name _;
  # Redirect HTTP to HTTPS if you have certs;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl http2;
  server_name _;
  ssl_certificate /run/secrets/moqui-cert.pem;
  ssl_certificate_key /run/secrets/moqui-key.pem;

  location / {
    proxy_pass http://moqui_upstream;
    include /etc/nginx/snippets/moqui-proxy.conf;
  }
}