apiVersion: 1

# Grafana datasources for local Docker Compose environment.
# Database: Postgres (single node), Search: OpenSearch (single node).
# For production Swarm datasources see datasource.yml.

datasources:
  - name: moqui-database
    type: postgres
    url: moqui-database:5432
    user: moqui
    database: moqui
    jsonData:
      sslmode: "disable"
      postgresVersion: 1400
      timescaledb: false
    secureJsonData:
      password: "moqui"

  - name: moqui-search
    type: elasticsearch
    url: http://moqui-search:9200
    database: "[default_]YYYY.MM.DD"
    jsonData:
      esVersion: "7.10.0"
      timeField: "@timestamp"
      logMessageField: message
      logLevelField: level
